name: Sync Meshik on Commit

on:
  push:
    branches:
      - serge  # Change this to the branch you want to trigger on

jobs:
  sync-meshik:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Ostrinder
      uses: actions/checkout@v2
      with:
        repository: forecaster-cyber/ostrinder
        ref: ${{ github.event.before || github.sha }}

    - name: Copy files to Meshik
      run: |
        cp -r build/web/* ../Meshik/  # Adjust the source and destination paths accordingly
      working-directory: Meshik  # Adjust if needed

    - name: Commit and push changes to Meshik
      run: |
        git config --global user.email "forecaster1310@gmail.com"
        git config --global user.name "GitHub Actions"
        git add .
        git commit -m "Sync files from Ostrinder"
        git push
      working-directory: Meshik  # Adjust if needed
